version: "3"
services:
  server:
    build: ./server
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - 3000:3000

  frontend:
    build: ./frontend
    command: command